// Stylelint config rules
module.exports = {
  rules: {
    'block-no-empty': true,
    'color-no-invalid-hex': true,
    'color-named': 'always-where-possible',
    'comment-empty-line-before': 'always',
    'comment-no-empty': true,
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'function-comma-space-after': 'always',
    'function-url-quotes': 'always',
    'function-max-empty-lines': 1,
    'function-url-data-uris': 'never',
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-vendor-prefix': true,
    'max-empty-lines': 4,
    'number-leading-zero': 'never',
    'number-no-trailing-zeros': true,
    'property-no-vendor-prefix': true,
    'declaration-block-no-duplicate-properties': true,
    'block-opening-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always',
    'block-closing-brace-empty-line-before': 'never',
    'declaration-block-trailing-semicolon': 'always',
    'selector-list-comma-space-before': 'never',
    'selector-list-comma-newline-after': 'always',
    'selector-no-id': true,
    'selector-max-compound-selectors': 3,
    'string-no-newline': true,
    'string-quotes': 'double',
    'value-no-vendor-prefix': true,
    'length-zero-no-unit': true,
    'unit-blacklist': ['pt', 'pic', 'vh', 'vw', 'vmin', 'hmin'],
    'property-no-unknown': true,
    'max-nesting-depth': 2
  }
};
